root: true
env:
  es2021: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - "@typescript-eslint"
extends:
  - "plugin:@typescript-eslint/recommended"
  - "htmlacademy/node"
rules:
  object-curly-spacing:
    - error
    - always
  "@typescript-eslint/type-annotation-spacing":
    - error
    - before: false
      after: true
  semi:
    - error
    - always
overrides:
  - files:
      - "*.ts"
      - "*.tsx"
    rules:
      # для TS-файлов
      "@typescript-eslint/semi":
        - error
        - always
      semi: off
